### ISSUE TITLE
ValueError: negative seek value -9

### ISSUE THREAD

**Issue by WaztWolf** [ain-soph/ddb-extraction#4]
Hey im trying to Pack to DDB my samples but im getting this error
PS L:\DDB-Packer> python pack_ddb.py --src_path "L:\OpenUtau\Singers\WaztOkamineVUDEVDB\Wazt Okamine" --dst_path "L:\.VOCALOID_VOICES\VoiceDB\Wazt_Okamine_V4_Beta\BM9KD8N6MLYP2MEK" 
Reading DDI...
Traceback (most recent call last):
  File "L:\DDB-Packer\pack_ddb.py", line 234, in <module>
    main()
  File "L:\DDB-Packer\pack_ddb.py", line 79, in main
    ddi_model.read()
  File "L:\DDB-Packer\utils\ddi_utils.py", line 162, in read
    self.ddi_data.seek(art_offset)
ValueError: negative seek value -9
i dont know if its an issue or its an error of me but i need help 
![vvvvvvvvvvvvv](https://github.com/ain-soph/ddb-extraction/assets/112556610/5a3c1771-ebcf-427b-acdf-3bdfd402e704)

**Comment by multitrack-collector** [comment]
What version of python are you using again?

**Comment by multitrack-collector** [comment]
Likely issue with newer version of python 3.11 and above

**Comment by ain-soph** [comment]
I assume this is issue for some fork of this repo? I don't have `pack_ddb.py` in the repo.
